package org.example.bookstore.controller;

import org.example.bookstore.dto.BookRequestDto;
import org.example.bookstore.dto.BookResponseDto;
import org.example.bookstore.service.BookService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * LabController - Experimental endpoints for learning Hibernate internals.
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * PURPOSE:
 * ═══════════════════════════════════════════════════════════════════════════════
 * These endpoints are NOT for production use.
 * They're designed to isolate and observe specific Hibernate behaviors.
 *
 * Each endpoint demonstrates ONE or TWO concepts, making it easy to:
 * - Predict expected SQL
 * - Observe actual SQL (in logs)
 * - Compare theory vs practice
 * - Debug misunderstandings
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * LEARNING PROGRESSION:
 * ═══════════════════════════════════════════════════════════════════════════════
 * Commit 01: /lab/create-book     → Entity creation & SQL generation
 * Commit 01: /lab/get-book/{id}   → Entity retrieval & SELECT queries
 *
 * Future commits will add:
 * Commit 03: /lab/entity-lifecycle   → Observe TRANSIENT/MANAGED/DETACHED states
 * Commit 05: /lab/transaction-demo   → See @Transactional behavior
 * Commit 07: /lab/dirty-checking     → Modify entity, observe UPDATE SQL
 * Commit 08: /lab/flush-demo         → Compare save() vs flush() vs commit()
 * Commit 12: /lab/pagination-demo    → Observe pagination queries
 * Commit 13: /lab/batch-insert       → Performance of bulk inserts
 * Commit 14: /lab/cache-demo         → First-level cache behavior
 * Etc.
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * HOW TO USE:
 * ═══════════════════════════════════════════════════════════════════════════════
 * METHODOLOGY (Active Learning):
 *
 * 1. READ THE JAVADOC on the endpoint method
 *    - Understand what concept it demonstrates
 *    - Look at "LAB OBJECTIVE" section
 *
 * 2. PREDICT (before calling endpoint)
 *    - What SQL should be generated?
 *    - How many queries?
 *    - What parameters will be bound?
 *    - What HTTP status code?
 *
 * 3. EXECUTE (call the endpoint)
 *    Option A: Using curl
 *      curl -X POST http://localhost:8080/lab/create-book \
 *        -H "Content-Type: application/json" \
 *        -d '{...}'
 *
 *    Option B: Using IDE (IntelliJ)
 *      - File → New → HTTP Request
 *      - Type: POST http://localhost:8080/lab/create-book
 *      - Body: JSON
 *      - Click green arrow to execute
 *
 * 4. OBSERVE (check console logs)
 *    - Scroll through IDE console
 *    - Find "[SQL]" log lines → generated SQL
 *    - Find "[BIND]" log lines → parameter binding
 *    - Find "[RESULT]" lines → query results
 *
 * 5. COMPARE (theory vs reality)
 *    - Match actual SQL to your prediction
 *    - If different: trace why
 *    - Understand the difference
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * HOW TO OBSERVE SQL IN CONSOLE:
 * ═══════════════════════════════════════════════════════════════════════════════
 * application.properties already configures Hibernate logging:
 *
 * logging.level.org.hibernate.SQL=DEBUG
 * → Logs all SQL statements
 *
 * logging.level.org.hibernate.orm.jdbc.bind=TRACE
 * → Logs parameter binding (the VALUES in INSERT)
 *
 * spring.jpa.properties.hibernate.format_sql=true
 * → Formats SQL with newlines (easier to read)
 *
 * spring.jpa.properties.hibernate.use_sql_comments=true
 * → Adds comments in SQL showing which entity/field generated it
 *
 * EXAMPLE OUTPUT (when you call an endpoint):
 *
 * 2024-11-15 10:30:45.123  INFO  o.e.b.c.LabController     : Lab test: Creating book...
 * 2024-11-15 10:30:45.234  DEBUG o.h.SQL                   : insert into books (isbn, price, published_year, title) values (?, ?, ?, ?)
 * 2024-11-15 10:30:45.235  TRACE o.h.orm.jdbc.bind         : binding parameter [1] as [VARCHAR] - [978-0134685991]
 * 2024-11-15 10:30:45.235  TRACE o.h.orm.jdbc.bind         : binding parameter [2] as [NUMERIC] - [45.99]
 * 2024-11-15 10:30:45.235  TRACE o.h.orm.jdbc.bind         : binding parameter [3] as [INTEGER] - [2018]
 * 2024-11-15 10:30:45.235  TRACE o.h.orm.jdbc.bind         : binding parameter [4] as [VARCHAR] - [Effective Java]
 * 2024-11-15 10:30:45.250  INFO  o.e.b.c.LabController     : Lab test: Complete!
 *
 * INTERPRETATION:
 * - "insert into books ..." → SQL generated by Hibernate
 * - "binding parameter [1] as [VARCHAR] - [978-0134685991]" → First parameter is ISBN
 * - Occurs after transaction commit (this is what we're learning!)
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 * DEBUGGING WITH BREAKPOINTS:
 * ═══════════════════════════════════════════════════════════════════════════════
 * For deeper learning, add breakpoints:
 *
 * 1. Click gutter in IDE (left margin)
 * 2. Set breakpoint on the method you're studying
 * 3. Run application with debugger (Shift+F9 in IntelliJ)
 * 4. Call endpoint via curl/HTTP client
 * 5. Debugger pauses at breakpoint
 * 6. Step through code (F8 = step over, F7 = step into)
 * 7. Watch variables panel to see entity state changes
 * 8. Look at "Evaluate Expression" to query Persistence Context
 *
 * @see org.springframework.web.bind.annotation.RestController
 */
@RestController
@RequestMapping("/lab")  // Base path: /lab
@RequiredArgsConstructor
public class LabController {
    private final BookService bookService;

    /**
     * Create a book and observe entity lifecycle + SQL generation.
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * LAB OBJECTIVE (Commit 01):
     * ═══════════════════════════════════════════════════════════════════════════════
     * Observe the complete lifecycle of entity creation:
     * 1. Entity state changes (Transient → Managed)
     * 2. Exactly WHEN INSERT SQL is generated (at transaction commit, not save())
     * 3. Parameter binding in console logs
     * 4. When Persistence Context tracks the entity
     * 5. When database generates the ID
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * PREDICTION EXERCISE (Before calling this endpoint):
     * ═══════════════════════════════════════════════════════════════════════════════
     * Answer these questions BEFORE running:
     *
     * Q1: When will SQL INSERT be executed?
     *     a) Immediately when repository.save() is called
     *     b) When @Transactional method ends (transaction commit)
     *     c) Never (INSERT isn't needed for save)
     *     Answer: B ✓
     *
     * Q2: How many times will INSERT execute for one book?
     *     a) Zero (save doesn't actually persist)
     *     b) Once (one book = one INSERT)
     *     c) Twice (one for save, one for commit)
     *     Answer: B ✓
     *
     * Q3: What happens if we remove @Transactional from BookService.createBook?
     *     a) Still works (transaction not needed)
     *     b) Works but slower (no caching)
     *     c) Fails (no transaction = no persistence)
     *     Answer: C ✓
     *
     * Q4: When is the generated ID (from database) available?
     *     a) Never (client must provide ID)
     *     b) After repository.save() returns
     *     c) After transaction commits (implicit flush)
     *     Answer: B/C (depends on flush strategy, usually B for IDENTITY)
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * HTTP:
     * ═══════════════════════════════════════════════════════════════════════════════
     * POST /lab/create-book
     * Content-Type: application/json
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * REQUEST BODY:
     * ═══════════════════════════════════════════════════════════════════════════════
     * {
     *   "title": "Clean Code",
     *   "isbn": "978-0132350884",
     *   "price": 50.00,
     *   "publishedYear": 2008
     * }
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * EXPECTED CONSOLE OUTPUT:
     * ═══════════════════════════════════════════════════════════════════════════════
     * [INFO] Lab endpoint: createBook invoked
     * [DEBUG org.hibernate.SQL] insert into books (isbn, price, published_year, title) values (?, ?, ?, ?)
     * [TRACE org.hibernate.orm.jdbc.bind] binding parameter [1] as [VARCHAR] - [978-0132350884]
     * [TRACE org.hibernate.orm.jdbc.bind] binding parameter [2] as [NUMERIC] - [50.0]
     * [TRACE org.hibernate.orm.jdbc.bind] binding parameter [3] as [INTEGER] - [2008]
     * [TRACE org.hibernate.orm.jdbc.bind] binding parameter [4] as [VARCHAR] - [Clean Code]
     * [INFO] Lab endpoint: createBook complete! (Book persisted with ID = X)
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * WHAT'S HAPPENING (Step-by-step):
     * ═══════════════════════════════════════════════════════════════════════════════
     * 1. HTTP POST /lab/create-book received
     * 2. BookRequestDto deserialized from JSON
     * 3. bookService.createBook() called
     * 4. @Transactional starts transaction
     * 5. DTO → Entity conversion (MapStruct)
     * 6. repository.save(book)
     *    - Adds to Persistence Context
     *    - Book state: TRANSIENT → MANAGED
     *    - NO SQL executed yet
     * 7. entity → DTO conversion (MapStruct)
     *    - Accesses book.id (causes implicit flush before returning)
     * 8. @Transactional intercepts method return
     *    - Calls flush() (if not done)
     *    - Executes INSERT SQL
     * 9. Calls commit() on transaction
     * 10. Returns BookResponseDto with ID
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * WHY THIS MATTERS (Learning Value):
     * ═══════════════════════════════════════════════════════════════════════════════
     * This lab teaches:
     * - The difference between save() (adds to context) and commit() (executes SQL)
     * - Why @Transactional is CRITICAL for persistence
     * - When Hibernate generates SQL
     * - How parameter binding works
     * - Database-generated IDs (IDENTITY strategy)
     *
     * Common Misconception: save() = INSERT SQL
     * Reality: save() = add to context, INSERT SQL happens at commit
     * This is a leading cause of bugs in Hibernate apps!
     *
     * @param requestDto - book data (title, isbn, price, publishedYear)
     * @return ResponseEntity with 201 Created and the persisted book
     *
     * @see Commit 01: Entity Mapping & Basic Persistence
     * @see BookService#createBook
     * @see org.springframework.transaction.annotation.Transactional
     */
    @PostMapping("/create-book")
    public ResponseEntity<BookResponseDto> createBook(@RequestBody BookRequestDto requestDto) {
        System.out.println("═══════════════════════════════════════════════════════════════");
        System.out.println("LAB ENDPOINT: createBook() invoked");
        System.out.println("Request DTO: " + requestDto);
        System.out.println("═══════════════════════════════════════════════════════════════");
        System.out.println("STEP 1: Calling bookService.createBook()...");
        System.out.println("        @Transactional will START a transaction here");
        
        // Call service (which is @Transactional)
        // This is where the magic happens!
        BookResponseDto response = bookService.createBook(requestDto);
        
        System.out.println("STEP 2: bookService.createBook() returned");
        System.out.println("        Response DTO: " + response);
        System.out.println("        Book ID is now: " + response.id());
        System.out.println("        @Transactional will COMMIT the transaction here");
        System.out.println("═══════════════════════════════════════════════════════════════");
        System.out.println("LAB ENDPOINT: createBook() complete!");
        System.out.println("═══════════════════════════════════════════════════════════════\n");
        
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Retrieve a book and observe SELECT query.
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * LAB OBJECTIVE (Commit 01):
     * ═══════════════════════════════════════════════════════════════════════════════
     * Observe:
     * 1. SELECT SQL generation
     * 2. Parameter binding (WHERE id = ?)
     * 3. Entity state after loading from database (MANAGED)
     * 4. NULL handling (if book not found)
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * PREDICTION EXERCISE:
     * ═══════════════════════════════════════════════════════════════════════════════
     * Q1: What SQL will be generated for getBook(1)?
     *     Answer: SELECT * FROM books WHERE id = 1
     *
     * Q2: How is parameter binding used?
     *     Answer: SELECT ... WHERE id = ? (? is bound to 1)
     *
     * Q3: What happens if book ID doesn't exist?
     *     Answer: Exception thrown → HTTP 404 Not Found (handled by GlobalExceptionHandler)
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * HTTP:
     * ═══════════════════════════════════════════════════════════════════════════════
     * GET /lab/get-book/1
     * (No request body)
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * EXPECTED CONSOLE OUTPUT:
     * ═══════════════════════════════════════════════════════════════════════════════
     * [DEBUG org.hibernate.SQL] select b1_0.id, b1_0.isbn, b1_0.price, b1_0.published_year, b1_0.title from books b1_0 where b1_0.id=?
     * [TRACE org.hibernate.orm.jdbc.bind] binding parameter [1] as [BIGINT] - [1]
     *
     * ═══════════════════════════════════════════════════════════════════════════════
     * WHAT'S HAPPENING:
     * ═══════════════════════════════════════════════════════════════════════════════
     * 1. HTTP GET /lab/get-book/1
     * 2. Spring extracts id = 1 from URL
     * 3. bookService.getBook(1) called
     * 4. repository.findById(1) called
     * 5. Hibernate generates SELECT * WHERE id = 1
     * 6. Database returns result
     * 7. Hibernate creates Book instance, populates fields
     * 8. Book added to Persistence Context (MANAGED)
     * 9. Returned to service
     * 10. Converted to DTO
     * 11. Returned as JSON response
     *
     * @param id - book ID from URL (e.g., 1, 2, 3)
     * @return ResponseEntity with 200 OK and the book data
     *
     * @see Commit 01: Entity Retrieval
     * @see BookService#getBook
     */
    @GetMapping("/get-book/{id}")
    public ResponseEntity<BookResponseDto> getBook(@PathVariable Long id) {
        System.out.println("═══════════════════════════════════════════════════════════════");
        System.out.println("LAB ENDPOINT: getBook(" + id + ") invoked");
        System.out.println("═══════════════════════════════════════════════════════════════");
        System.out.println("STEP 1: Calling bookService.getBook(" + id + ")...");
        
        // Call service to fetch book
        BookResponseDto response = bookService.getBook(id);
        
        System.out.println("STEP 2: bookService.getBook() returned");
        System.out.println("        Response DTO: " + response);
        System.out.println("═══════════════════════════════════════════════════════════════");
        System.out.println("LAB ENDPOINT: getBook() complete!");
        System.out.println("═══════════════════════════════════════════════════════════════\n");
        
        return ResponseEntity.ok(response);
    }
}
